# Generated by Django 5.0.6 on 2024-06-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_product_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="No Description"),
        ),
    ]
