# Generated by Django 5.0.6 on 2024-09-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="isRecommended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default=None, max_length=120),
        ),
    ]
