POST http://127.0.0.1:8000/login/
Content-Type: application/json

{ "email": "kamal.hamza@outlook.com", "password": "123" }

####

POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{ "email" :"kamal.hamza@outlook.com", "username": "hkamal", "password": "123" }

####

GET http://127.0.0.1:8000/signup/
Content-Type: application/json

####

POST http://127.0.0.1:8000/create-product/
Content-Type: application/json
Authorization: Token e9979feb6ca9e1ffb3053fb56dea1a95a64d4673

{ "title": "sample product", "description": "Sample Description" }

####

POST http://127.0.0.1:8000/create-product/
Content-Type: application/json    
Authorization: Token e9979feb6ca9e1ffb3053fb56dea1a95a64d4673

{ "title": "sample product" }

####

GET http://127.0.0.1:8000/search/?search=the

####

POST http://127.0.0.1:8000/products/
Content-Type: application/json
Authorization: Token e9979feb6ca9e1ffb3053fb56dea1a95a64d4673

{ "id": "1" }