POST http://127.0.0.1:8000/login/
Content-Type: application/json

{ "email": "kamal.hamza@outlook.com", "password": "123" }

####

POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{ "email" :"kamal.hamza@outlook.com", "username": "hkamal", "password": "123" }

####

GET http://127.0.0.1:8000/signup/
Content-Type: application/json

####

POST http://127.0.0.1:8000/products/
Content-Type: application/json
Authorization: Token 44b38190ce8a477c15e5e7343c6c7f8e80cc1c3b

{ "title": "sample product", "description": "Sample Description" }

####

POST http://127.0.0.1:8000/products/
Content-Type: application/json
Authorization: Token 44b38190ce8a477c15e5e7343c6c7f8e80cc1c3b

{ "title": "sample product" }